### ISSUE TITLE
new release not triggered with conventionalcommits

### ISSUE THREAD

**Issue by ticapix** [semantic-release-action/next-release-version#35]
Hello,

I'm trying to setup `semantic-release-action/next-release-version` with [conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits)

I configured by [`.releaserc.json`](https://github.com/eclipse-dataspace-cap/cap-ontology/blob/main/.releaserc.json#L9) to set the `commit-analyzer` to `conventionalcommits` but the `feat!:` commit doesn't trigger a release.

https://github.com/eclipse-dataspace-cap/cap-ontology/actions/runs/14803965208/job/41568779415

```text
[9:52:06 PM] [semantic-release] › ℹ  Running semantic-release version 24.2.3
[9:52:07 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-export-data"
[9:52:07 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:52:07 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "semantic-release-export-data"
[9:52:09 PM] [semantic-release] › ⚠  Run automated release from branch main on repository https://github.com/eclipse-dataspace-cap/cap-ontology.git in dry-run mode
[9:52:09 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:52:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-export-data"
[9:52:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "semantic-release-export-data"
[9:52:09 PM] [semantic-release] › ℹ  Found git tag v1.0.0 associated with version 1.0.0 on branch main
[9:52:09 PM] [semantic-release] › ℹ  Found 17 commits since last release
[9:52:09 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[...]
[9:52:09 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat!: turn all range to ObjectProperty except date. Remove mandatory id
[9:52:09 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[9:52:09 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 17 commits complete: no release
[9:52:09 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[9:52:09 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

Any idea what am I missing ?

Thank you,
Pierre

**Comment by ticapix** [comment]
Hello,

I decided to go directly with `semantic-release` with `dry_run: true`

My working config is 

```yaml
  get-next-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-release-version: ${{ steps.get-next-version.outputs.new_release_version }}
      new-release-published: ${{ steps.get-next-version.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        id: get-next-version
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/github
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
